/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SalaryBreakdown = IDL.Record({
  'meshSalary' : IDL.Int,
  'totalAttendanceSalary' : IDL.Int,
  'labourId' : IDL.Nat,
  'netSalary' : IDL.Int,
  'totalAdvances' : IDL.Int,
  'labourName' : IDL.Text,
  'bedSalary' : IDL.Int,
  'paperSalary' : IDL.Int,
});
export const Advance = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'labourId' : IDL.Nat,
  'amount' : IDL.Int,
  'contractId' : IDL.Nat,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'isSettled' : IDL.Bool,
  'name' : IDL.Text,
  'machineExp' : IDL.Int,
  'meshColumns' : IDL.Vec(IDL.Text),
  'bedAmount' : IDL.Int,
  'paperAmount' : IDL.Int,
  'meshAmount' : IDL.Int,
  'contractAmount' : IDL.Int,
  'multiplierValue' : IDL.Float64,
});
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const ColumnType = IDL.Variant({
  'bed' : IDL.Null,
  'mesh' : IDL.Nat,
  'paper' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Nat,
  'columnType' : ColumnType,
  'value' : IDL.Text,
  'labourId' : IDL.Nat,
  'contractId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calculateNetSalaries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SalaryBreakdown)],
      ['query'],
    ),
  'createAdvance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createContract' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Int,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createLabour' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'deleteContract' : IDL.Func([IDL.Nat], [], []),
  'getAdvancesByContract' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAdvancesByLabour' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
  'getAttendanceByContract' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
  'saveAttendance' : IDL.Func(
      [IDL.Nat, IDL.Nat, ColumnType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'settleContract' : IDL.Func([IDL.Nat], [], []),
  'unsettleContract' : IDL.Func([IDL.Nat], [], []),
  'updateContract' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Int,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateLabour' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SalaryBreakdown = IDL.Record({
    'meshSalary' : IDL.Int,
    'totalAttendanceSalary' : IDL.Int,
    'labourId' : IDL.Nat,
    'netSalary' : IDL.Int,
    'totalAdvances' : IDL.Int,
    'labourName' : IDL.Text,
    'bedSalary' : IDL.Int,
    'paperSalary' : IDL.Int,
  });
  const Advance = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'labourId' : IDL.Nat,
    'amount' : IDL.Int,
    'contractId' : IDL.Nat,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'isSettled' : IDL.Bool,
    'name' : IDL.Text,
    'machineExp' : IDL.Int,
    'meshColumns' : IDL.Vec(IDL.Text),
    'bedAmount' : IDL.Int,
    'paperAmount' : IDL.Int,
    'meshAmount' : IDL.Int,
    'contractAmount' : IDL.Int,
    'multiplierValue' : IDL.Float64,
  });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ColumnType = IDL.Variant({
    'bed' : IDL.Null,
    'mesh' : IDL.Nat,
    'paper' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Nat,
    'columnType' : ColumnType,
    'value' : IDL.Text,
    'labourId' : IDL.Nat,
    'contractId' : IDL.Nat,
  });
  
  return IDL.Service({
    'calculateNetSalaries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SalaryBreakdown)],
        ['query'],
      ),
    'createAdvance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createContract' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Int,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createLabour' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'deleteContract' : IDL.Func([IDL.Nat], [], []),
    'getAdvancesByContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Advance)],
        ['query'],
      ),
    'getAdvancesByLabour' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
    'getAttendanceByContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
    'saveAttendance' : IDL.Func(
        [IDL.Nat, IDL.Nat, ColumnType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'settleContract' : IDL.Func([IDL.Nat], [], []),
    'unsettleContract' : IDL.Func([IDL.Nat], [], []),
    'updateContract' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Int,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateLabour' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };