/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLogEntry {
  'createdAt' : string,
  'contractName' : string,
  'contractId' : bigint,
  'settledAt' : [] | [string],
}
export interface Advance {
  'id' : bigint,
  'note' : string,
  'labourId' : bigint,
  'timestamp' : string,
  'amount' : bigint,
  'contractId' : bigint,
}
export interface Attendance {
  'id' : bigint,
  'columnType' : ColumnType,
  'value' : string,
  'labourId' : bigint,
  'contractId' : bigint,
}
export interface AttendanceNote {
  'id' : bigint,
  'note' : string,
  'labourId' : bigint,
  'contractId' : bigint,
}
export type ColumnType = { 'bed' : null } |
  { 'mesh' : bigint } |
  { 'paper' : null };
export interface Contract {
  'id' : bigint,
  'isSettled' : boolean,
  'name' : string,
  'createdAt' : string,
  'machineExp' : bigint,
  'meshColumns' : Array<string>,
  'bedAmount' : bigint,
  'paperAmount' : bigint,
  'meshAmount' : bigint,
  'contractAmount' : bigint,
  'multiplierValue' : number,
  'settledAt' : [] | [string],
}
export interface Group { 'id' : bigint, 'name' : string }
export interface Holiday {
  'id' : bigint,
  'columnKey' : string,
  'contractId' : bigint,
}
export interface Labour {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'groupId' : [] | [bigint],
  'phone' : [] | [string],
}
export interface SalaryBreakdown {
  'meshSalary' : bigint,
  'totalAttendanceSalary' : bigint,
  'labourId' : bigint,
  'netSalary' : bigint,
  'totalAdvances' : bigint,
  'labourName' : string,
  'bedSalary' : bigint,
  'paperSalary' : bigint,
}
export interface WorkingTodayEntry { 'ts' : string, 'count' : bigint }
export interface _SERVICE {
  'calculateNetSalaries' : ActorMethod<[bigint], Array<SalaryBreakdown>>,
  'changeAdminCredentials' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'createAdvance' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    bigint
  >,
  'createContract' : ActorMethod<
    [
      string,
      number,
      bigint,
      bigint,
      [] | [bigint],
      [] | [bigint],
      Array<string>,
      string,
    ],
    bigint
  >,
  'createGroup' : ActorMethod<[string], bigint>,
  'createLabour' : ActorMethod<[string, [] | [string], [] | [bigint]], bigint>,
  'deleteAdvance' : ActorMethod<[bigint], undefined>,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'deleteGroup' : ActorMethod<[bigint], undefined>,
  'deleteLabour' : ActorMethod<[bigint], undefined>,
  'getActivityLog' : ActorMethod<[], Array<ActivityLogEntry>>,
  'getAdvancesByContract' : ActorMethod<[bigint], Array<Advance>>,
  'getAdvancesByLabour' : ActorMethod<[bigint], Array<Advance>>,
  'getAllAdvances' : ActorMethod<[], Array<Advance>>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllLabours' : ActorMethod<[], Array<Labour>>,
  'getAttendanceByContract' : ActorMethod<[bigint], Array<Attendance>>,
  'getContract' : ActorMethod<[bigint], Contract>,
  'getHolidaysByContract' : ActorMethod<[bigint], Array<Holiday>>,
  'getNotesByContract' : ActorMethod<[bigint], Array<AttendanceNote>>,
  'getWorkingTodayMap' : ActorMethod<[], Array<[bigint, WorkingTodayEntry]>>,
  'hasAdminCredentials' : ActorMethod<[], boolean>,
  'markHoliday' : ActorMethod<[bigint, string], bigint>,
  'recordWorkingToday' : ActorMethod<[bigint, bigint, string], undefined>,
  'removeHoliday' : ActorMethod<[bigint, string], undefined>,
  'saveAttendance' : ActorMethod<[bigint, bigint, ColumnType, string], bigint>,
  'saveAttendanceNote' : ActorMethod<[bigint, bigint, string], bigint>,
  'setAdminCredentials' : ActorMethod<[string, string], boolean>,
  'setLabourActive' : ActorMethod<[bigint, boolean], undefined>,
  'settleContract' : ActorMethod<[bigint, string], undefined>,
  'unsettleContract' : ActorMethod<[bigint], undefined>,
  'updateAdvance' : ActorMethod<[bigint, bigint, string], undefined>,
  'updateContract' : ActorMethod<
    [
      bigint,
      string,
      number,
      bigint,
      bigint,
      [] | [bigint],
      [] | [bigint],
      Array<string>,
    ],
    undefined
  >,
  'updateLabour' : ActorMethod<
    [bigint, string, [] | [string], [] | [bigint]],
    undefined
  >,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];