/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advance {
  'id' : bigint,
  'note' : string,
  'labourId' : bigint,
  'amount' : bigint,
  'contractId' : bigint,
}
export interface Attendance {
  'id' : bigint,
  'columnType' : ColumnType,
  'value' : string,
  'labourId' : bigint,
  'contractId' : bigint,
}
export type ColumnType = { 'bed' : null } |
  { 'mesh' : bigint } |
  { 'paper' : null };
export interface Contract {
  'id' : bigint,
  'isSettled' : boolean,
  'name' : string,
  'machineExp' : bigint,
  'meshColumns' : Array<string>,
  'bedAmount' : bigint,
  'paperAmount' : bigint,
  'meshAmount' : bigint,
  'contractAmount' : bigint,
  'multiplierValue' : number,
}
export interface Labour {
  'id' : bigint,
  'name' : string,
  'phone' : [] | [string],
}
export interface SalaryBreakdown {
  'meshSalary' : bigint,
  'totalAttendanceSalary' : bigint,
  'labourId' : bigint,
  'netSalary' : bigint,
  'totalAdvances' : bigint,
  'labourName' : string,
  'bedSalary' : bigint,
  'paperSalary' : bigint,
}
export interface _SERVICE {
  'calculateNetSalaries' : ActorMethod<[bigint], Array<SalaryBreakdown>>,
  'createAdvance' : ActorMethod<[bigint, bigint, bigint, string], bigint>,
  'createContract' : ActorMethod<
    [
      string,
      number,
      bigint,
      bigint,
      [] | [bigint],
      [] | [bigint],
      Array<string>,
    ],
    bigint
  >,
  'createLabour' : ActorMethod<[string, [] | [string]], bigint>,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'getAdvancesByContract' : ActorMethod<[bigint], Array<Advance>>,
  'getAdvancesByLabour' : ActorMethod<[bigint], Array<Advance>>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllLabours' : ActorMethod<[], Array<Labour>>,
  'getAttendanceByContract' : ActorMethod<[bigint], Array<Attendance>>,
  'getContract' : ActorMethod<[bigint], Contract>,
  'saveAttendance' : ActorMethod<[bigint, bigint, ColumnType, string], bigint>,
  'settleContract' : ActorMethod<[bigint], undefined>,
  'unsettleContract' : ActorMethod<[bigint], undefined>,
  'updateContract' : ActorMethod<
    [
      bigint,
      string,
      number,
      bigint,
      bigint,
      [] | [bigint],
      [] | [bigint],
      Array<string>,
    ],
    undefined
  >,
  'updateLabour' : ActorMethod<[bigint, string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];