/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    name: string;
    isActive: boolean;
    groupId?: bigint;
    phone?: string;
}
export interface SalaryBreakdown {
    meshSalary: bigint;
    totalAttendanceSalary: bigint;
    labourId: bigint;
    netSalary: bigint;
    totalAdvances: bigint;
    labourName: string;
    bedSalary: bigint;
    paperSalary: bigint;
}
export interface WorkingTodayEntry {
    ts: string;
    count: bigint;
}
export interface AttendanceNote {
    id: bigint;
    note: string;
    labourId: bigint;
    contractId: bigint;
}
export interface Attendance {
    id: bigint;
    columnType: ColumnType;
    value: string;
    labourId: bigint;
    contractId: bigint;
}
export interface Group {
    id: bigint;
    name: string;
}
export interface Contract {
    id: bigint;
    isSettled: boolean;
    name: string;
    createdAt: string;
    machineExp: bigint;
    meshColumns: Array<string>;
    bedAmount: bigint;
    paperAmount: bigint;
    meshAmount: bigint;
    contractAmount: bigint;
    multiplierValue: number;
    settledAt?: string;
}
export interface Holiday {
    id: bigint;
    columnKey: string;
    contractId: bigint;
}
export type ColumnType = {
    __kind__: "bed";
    bed: null;
} | {
    __kind__: "mesh";
    mesh: bigint;
} | {
    __kind__: "paper";
    paper: null;
};
export interface Advance {
    id: bigint;
    note: string;
    labourId: bigint;
    timestamp: string;
    amount: bigint;
    contractId: bigint;
}
export interface ActivityLogEntry {
    createdAt: string;
    contractName: string;
    contractId: bigint;
    settledAt?: string;
}
export interface backendInterface {
    calculateNetSalaries(contractId: bigint): Promise<Array<SalaryBreakdown>>;
    changeAdminCredentials(oldToken: string, oldPassword: string, newToken: string, newPassword: string): Promise<boolean>;
    createAdvance(contractId: bigint, labourId: bigint, amount: bigint, note: string, timestamp: string): Promise<bigint>;
    createContract(name: string, multiplierValue: number, contractAmount: bigint, machineExp: bigint, bedAmount: bigint | null, paperAmount: bigint | null, meshColumns: Array<string>, createdAt: string): Promise<bigint>;
    createGroup(name: string): Promise<bigint>;
    createLabour(name: string, phone: string | null, groupId: bigint | null): Promise<bigint>;
    deleteAdvance(id: bigint): Promise<void>;
    deleteContract(id: bigint): Promise<void>;
    deleteGroup(id: bigint): Promise<void>;
    deleteLabour(id: bigint): Promise<void>;
    getActivityLog(): Promise<Array<ActivityLogEntry>>;
    getAdvancesByContract(contractId: bigint): Promise<Array<Advance>>;
    getAdvancesByLabour(labourId: bigint): Promise<Array<Advance>>;
    getAllAdvances(): Promise<Array<Advance>>;
    getAllContracts(): Promise<Array<Contract>>;
    getAllGroups(): Promise<Array<Group>>;
    getAllLabours(): Promise<Array<Labour>>;
    getAttendanceByContract(contractId: bigint): Promise<Array<Attendance>>;
    getContract(id: bigint): Promise<Contract>;
    getHolidaysByContract(contractId: bigint): Promise<Array<Holiday>>;
    getNotesByContract(contractId: bigint): Promise<Array<AttendanceNote>>;
    getWorkingTodayMap(): Promise<Array<[bigint, WorkingTodayEntry]>>;
    hasAdminCredentials(): Promise<boolean>;
    markHoliday(contractId: bigint, columnKey: string): Promise<bigint>;
    recordWorkingToday(contractId: bigint, count: bigint, ts: string): Promise<void>;
    removeHoliday(contractId: bigint, columnKey: string): Promise<void>;
    saveAttendance(contractId: bigint, labourId: bigint, columnType: ColumnType, value: string): Promise<bigint>;
    saveAttendanceNote(contractId: bigint, labourId: bigint, note: string): Promise<bigint>;
    setAdminCredentials(token: string, password: string): Promise<boolean>;
    setLabourActive(id: bigint, active: boolean): Promise<void>;
    settleContract(id: bigint, settledAt: string): Promise<void>;
    unsettleContract(id: bigint): Promise<void>;
    updateAdvance(id: bigint, amount: bigint, note: string): Promise<void>;
    updateContract(id: bigint, name: string, multiplierValue: number, contractAmount: bigint, machineExp: bigint, bedAmount: bigint | null, paperAmount: bigint | null, meshColumns: Array<string>): Promise<void>;
    updateLabour(id: bigint, name: string, phone: string | null, groupId: bigint | null): Promise<void>;
    verifyAdminCredentials(token: string, password: string): Promise<boolean>;
}
import type { ActivityLogEntry as _ActivityLogEntry, Attendance as _Attendance, ColumnType as _ColumnType, Contract as _Contract, Labour as _Labour } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateNetSalaries(arg0: bigint): Promise<Array<SalaryBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateNetSalaries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateNetSalaries(arg0);
            return result;
        }
    }
    async changeAdminCredentials(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createAdvance(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createContract(arg0: string, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint | null, arg5: bigint | null, arg6: Array<string>, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async createGroup(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async createLabour(arg0: string, arg1: string | null, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabour(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabour(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteAdvance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvance(arg0);
            return result;
        }
    }
    async deleteContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async deleteGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async deleteLabour(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabour(arg0);
            return result;
        }
    }
    async getActivityLog(): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdvancesByContract(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByContract(arg0);
            return result;
        }
    }
    async getAdvancesByLabour(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByLabour(arg0);
            return result;
        }
    }
    async getAllAdvances(): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdvances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdvances();
            return result;
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getAllLabours(): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabours();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabours();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByContract(arg0: bigint): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByContract(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByContract(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_Contract_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_Contract_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolidaysByContract(arg0: bigint): Promise<Array<Holiday>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolidaysByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolidaysByContract(arg0);
            return result;
        }
    }
    async getNotesByContract(arg0: bigint): Promise<Array<AttendanceNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByContract(arg0);
            return result;
        }
    }
    async getWorkingTodayMap(): Promise<Array<[bigint, WorkingTodayEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkingTodayMap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkingTodayMap();
            return result;
        }
    }
    async hasAdminCredentials(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAdminCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAdminCredentials();
            return result;
        }
    }
    async markHoliday(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markHoliday(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markHoliday(arg0, arg1);
            return result;
        }
    }
    async recordWorkingToday(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWorkingToday(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWorkingToday(arg0, arg1, arg2);
            return result;
        }
    }
    async removeHoliday(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHoliday(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHoliday(arg0, arg1);
            return result;
        }
    }
    async saveAttendance(arg0: bigint, arg1: bigint, arg2: ColumnType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAttendance(arg0, arg1, to_candid_ColumnType_n20(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAttendance(arg0, arg1, to_candid_ColumnType_n20(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveAttendanceNote(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAttendanceNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAttendanceNote(arg0, arg1, arg2);
            return result;
        }
    }
    async setAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminCredentials(arg0, arg1);
            return result;
        }
    }
    async setLabourActive(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLabourActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLabourActive(arg0, arg1);
            return result;
        }
    }
    async settleContract(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.settleContract(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleContract(arg0, arg1);
            return result;
        }
    }
    async unsettleContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsettleContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsettleContract(arg0);
            return result;
        }
    }
    async updateAdvance(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdvance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdvance(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint | null, arg6: bigint | null, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActivityLogEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLogEntry): ActivityLogEntry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ColumnType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColumnType): ColumnType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Labour_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Labour): Labour {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isSettled: boolean;
    name: string;
    createdAt: string;
    machineExp: bigint;
    meshColumns: Array<string>;
    bedAmount: bigint;
    paperAmount: bigint;
    meshAmount: bigint;
    contractAmount: bigint;
    multiplierValue: number;
    settledAt: [] | [string];
}): {
    id: bigint;
    isSettled: boolean;
    name: string;
    createdAt: string;
    machineExp: bigint;
    meshColumns: Array<string>;
    bedAmount: bigint;
    paperAmount: bigint;
    meshAmount: bigint;
    contractAmount: bigint;
    multiplierValue: number;
    settledAt?: string;
} {
    return {
        id: value.id,
        isSettled: value.isSettled,
        name: value.name,
        createdAt: value.createdAt,
        machineExp: value.machineExp,
        meshColumns: value.meshColumns,
        bedAmount: value.bedAmount,
        paperAmount: value.paperAmount,
        meshAmount: value.meshAmount,
        contractAmount: value.contractAmount,
        multiplierValue: value.multiplierValue,
        settledAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.settledAt))
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    isActive: boolean;
    groupId: [] | [bigint];
    phone: [] | [string];
}): {
    id: bigint;
    name: string;
    isActive: boolean;
    groupId?: bigint;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        isActive: value.isActive,
        groupId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.groupId)),
        phone: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    columnType: _ColumnType;
    value: string;
    labourId: bigint;
    contractId: bigint;
}): {
    id: bigint;
    columnType: ColumnType;
    value: string;
    labourId: bigint;
    contractId: bigint;
} {
    return {
        id: value.id,
        columnType: from_candid_ColumnType_n18(_uploadFile, _downloadFile, value.columnType),
        value: value.value,
        labourId: value.labourId,
        contractId: value.contractId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: string;
    contractName: string;
    contractId: bigint;
    settledAt: [] | [string];
}): {
    createdAt: string;
    contractName: string;
    contractId: bigint;
    settledAt?: string;
} {
    return {
        createdAt: value.createdAt,
        contractName: value.contractName,
        contractId: value.contractId,
        settledAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.settledAt))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bed: null;
} | {
    mesh: bigint;
} | {
    paper: null;
}): {
    __kind__: "bed";
    bed: null;
} | {
    __kind__: "mesh";
    mesh: bigint;
} | {
    __kind__: "paper";
    paper: null;
} {
    return "bed" in value ? {
        __kind__: "bed",
        bed: value.bed
    } : "mesh" in value ? {
        __kind__: "mesh",
        mesh: value.mesh
    } : "paper" in value ? {
        __kind__: "paper",
        paper: value.paper
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Labour>): Array<Labour> {
    return value.map((x)=>from_candid_Labour_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLogEntry>): Array<ActivityLogEntry> {
    return value.map((x)=>from_candid_ActivityLogEntry_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ColumnType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColumnType): _ColumnType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bed";
    bed: null;
} | {
    __kind__: "mesh";
    mesh: bigint;
} | {
    __kind__: "paper";
    paper: null;
}): {
    bed: null;
} | {
    mesh: bigint;
} | {
    paper: null;
} {
    return value.__kind__ === "bed" ? {
        bed: value.bed
    } : value.__kind__ === "mesh" ? {
        mesh: value.mesh
    } : value.__kind__ === "paper" ? {
        paper: value.paper
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
